# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];


  #boot.initrd.luks.tpmSupport = true;

  boot = {
    kernelModules = [ "kvm-intel" "acpi_call"];
    kernelParams = [
      "acpi_backlight=vendor"
      "pcie_aspm=force"
      "acpi_osi=Linux"
      "nmi_watchdog=0"
      "vm.laptop_mode=5"
    ];
    blacklistedKernelModules = [ ];
    extraModulePackages = [ pkgs.linuxPackages.acpi_call pkgs.tpacpi-bat ];
    extraModprobeConfig = ''
      options thinkpad_acpi fan_control=1
      options thinkpad_ec force_io=1
      options i915 enable_rc6=7 enable_fbc=1 semaphores=1 enable_dc=2
      options iwlwifi power_save=1 power_level=3
    '';

    loader = {
      systemd-boot.enable = true;
      efi.canTouchEfiVariables = true;
    };

    initrd = {
      availableKernelModules = [ 
        "xhci_pci" "ehci_pci" "ahci" "usb_storage" "sd_mod" "sdhci_pci"
      ];

      kernelModules = [
        "ext4"
        "tpm_tis"
        "tpm"
      ];

      luks = {
        devices = [
          {
            name = "root";
            device = "/dev/disk/by-uuid/29c814ea-93d9-4e9b-8f54-e6c841c921a7";
            preLVM = true; 
            allowDiscards = true;
          }
        ];
        mitigateDMAAttacks = true;
      };

    };
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/4cb6a0b7-9e6a-4a76-b6a3-d2db23046738";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/3EFC-A69A";
      fsType = "vfat";
    };

  hardware = {
    cpu.intel.updateMicrocode = true;
    trackpoint = {
      enable = true;
      emulateWheel = true;
      speed = 250;
      sensitivity = 140;
    };
    opengl = {
      driSupport = true;
      extraPackages = [ pkgs.vaapiIntel pkgs.libvdpau-va-gl pkgs.vaapiVdpau ];
    };
    pulseaudio = {
      enable = true;
    };
 };

  nix.maxJobs = lib.mkDefault 4;

  # RNG from TPM chip
  security.rngd.enable = true;

  swapDevices =
    [ { device = "/dev/disk/by-uuid/13e0f642-0fba-40e6-8fe5-f5254a07f4bd"; }
    ];

}

